[package]
name = "game-of-life"
version = "1.3.1"
publish = false
authors = ["Max Machon <max@machon.family>"]
edition = "2021"
readme = "README.md"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
ctrlc = "3.4.5"
drawille = "*"
rand = "*"
