[package]
name = "game-of-life"
version = "1.5.2"
publish = false
authors = ["Max Machon <max@machon.family>"]
edition = "2021"
readme = "README.md"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
ctrlc = "3.5.1"
drawille = "*"
rand = "*"
terminal_size = "0.4.3"
